steps:
  # Build the frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'Dockerfile.frontend'
      - '-t'
      - 'gcr.io/$PROJECT_ID/layer-frontend:latest'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/layer-frontend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY 